SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `USER`;
DROP TABLE IF EXISTS `BOARD`;
DROP TABLE IF EXISTS `COMMENT`;
DROP TABLE IF EXISTS `COMMENT_RECOMMEND`;
DROP TABLE IF EXISTS `BOARD_RECOMMEND`;
DROP TABLE IF EXISTS `ROLES`;
DROP TABLE IF EXISTS `AUTHORITY`;
DROP TABLE IF EXISTS `USER_ROLES`;
DROP TABLE IF EXISTS `ROLES_AUTHORITY`;
DROP TABLE IF EXISTS `AUDIT_LOG`;
DROP TABLE IF EXISTS `COMMENT_REPORT`;
DROP TABLE IF EXISTS `BOARD_REPORT`;
DROP TABLE IF EXISTS `PORTFOLIO`;
DROP TABLE IF EXISTS `PORTFOLIO_DETAIL`;
DROP TABLE IF EXISTS `BOOKMARK`;
DROP TABLE IF EXISTS `TRANSACTION`;
DROP TABLE IF EXISTS `ASSET`;
DROP TABLE IF EXISTS `ASSET_TYPE`;
SET foreign_key_checks = 1;

CREATE TABLE `USER` (
  `idx` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `email` VARCHAR(255) UNIQUE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `nickname` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20),
  `profile_img` LONGTEXT,
  `img_type` VARCHAR(30),
  `gender` VARCHAR(10),
  `age` INT,
  `suspend_until` DATETIME,
  `suspend_reason` VARCHAR(255),
  `created_at` DATETIME DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` DATETIME,
  `deleted_at` DATETIME,
  `deleted_reason` VARCHAR(255)
);

CREATE TABLE `ROLES` (
    `idx` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL
);

CREATE TABLE `AUTHORITY` (
    `idx` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL
);

CREATE TABLE `USER_ROLES` (
    `user_idx` BIGINT NOT NULL,
    `roles_idx` INT NOT NULL,
    PRIMARY KEY (`user_idx`, `roles_idx`)
);

CREATE TABLE `ROLES_AUTHORITY` (
    `roles_idx` INT NOT NULL,
    `authority_idx` INT NOT NULL,
    PRIMARY KEY (`roles_idx`, `authority_idx`)
);

CREATE TABLE `BOARD` (
    `idx` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `content` VARCHAR(1000) NOT NULL,
    `user_idx` BIGINT NOT NULL,
    `view_count` INT DEFAULT 0,
    `recommend_count` INT DEFAULT 0,
    `is_hided` BOOL DEFAULT FALSE,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME,
    `deleted_at` DATETIME
);

CREATE TABLE `BOARD_RECOMMEND` (
  `board_idx` BIGINT NOT NULL,
  `user_idx` BIGINT NOT NULL,
  `created_at` DATETIME DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY (board_idx, user_idx)
);

-- board_report 테이블 생성
CREATE TABLE `BOARD_REPORT` (
  `board_idx` BIGINT NOT NULL,
  `user_idx` BIGINT NOT NULL,
  `reason` VARCHAR(255),
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (board_idx, user_idx)
);

CREATE TABLE `COMMENT` (
  `idx` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `user_idx` BIGINT,
  `board_idx` BIGINT,
  `content` TEXT NOT NULL,
  `recommend_count` INT DEFAULT 0,
  `created_at` DATETIME DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` DATETIME,
  `deleted_at` DATETIME
);

CREATE TABLE `COMMENT_RECOMMEND` (
  `comment_idx` BIGINT NOT NULL,
  `user_idx` BIGINT NOT NULL,
  `created_at` DATETIME DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY (comment_idx, user_idx)
);

-- comment_report 테이블 생성
CREATE TABLE `COMMENT_REPORT` (
  `comment_idx` BIGINT NOT NULL,
  `user_idx` BIGINT NOT NULL,
  `reason` VARCHAR(255),
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (comment_idx, user_idx)
);

-- 포트폴리오(Portfolio) 테이블
CREATE TABLE `PORTFOLIO` (
    `idx` INT PRIMARY KEY AUTO_INCREMENT,
    `user_idx` BIGINT NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `description` VARCHAR(500),
    `created_at` DATETIME DEFAULT (CURRENT_TIMESTAMP),
    `updated_at` DATETIME,
    `deleted_at` DATETIME
);

-- 포트폴리오 디테일(PortfolioDetail) 테이블
CREATE TABLE `PORTFOLIO_DETAIL` (
    `idx` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `portfolio_idx` INT,
    `asset_idx` VARCHAR(20),
    `amount` DECIMAL(18,5),
    `average_purchase_price` DECIMAL(18,2),
    `total_purchase_price` DECIMAL(18,2),
    `dividend_month` VARCHAR(20),
    `dividend_amount` DECIMAL(18,2),
    `created_at` DATETIME DEFAULT (CURRENT_TIMESTAMP),
    `updated_at` DATETIME,
    `deleted_at` DATETIME
);

-- 자산(Asset) 테이블
CREATE TABLE `ASSET` (
    `idx` VARCHAR(20) PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `type_idx` INT NOT NULL,
    `price` DECIMAL(18,2),
    `updated_at` DATETIME
);

CREATE TABLE `ASSET_TYPE` (
    `idx` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL
);


-- 거래(Transaction) 테이블
CREATE TABLE `TRANSACTION` (
    `idx` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `user_idx` BIGINT,
    `portfolio_idx` INT,
    `asset_idx` VARCHAR(20),
    `type` VARCHAR(10),
    `amount` DECIMAL(18,5),
    `price_avg` DECIMAL(18,2),
    `profit` DECIMAL(18,2),
    `transaction_date` DATETIME
);

-- 북마크(Bookmark) 테이블
CREATE TABLE `BOOKMARK` (
    `idx` INT PRIMARY KEY AUTO_INCREMENT,
    `user_idx` BIGINT,
    `asset_idx` VARCHAR(20)
);


CREATE TABLE `AUDIT_LOG` (
    `idx` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `table_name` VARCHAR(100) NOT NULL,
    `user_idx` VARCHAR(100) NOT NULL,
    `row_id` INT,
    `operation` VARCHAR(10) NOT NULL,
    `column_name` VARCHAR(100),
    `old_value` VARCHAR(255),
    `new_value` VARCHAR(255),
    `reason` VARCHAR(255),
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX `IDX_BOARD_USER_IDX` ON `BOARD` (`user_idx`);
CREATE INDEX `IDX_BOARD_RECOMMEND_BOARD_IDX` ON `BOARD_RECOMMEND` (`board_idx`);
CREATE INDEX `IDX_BOARD_RECOMMEND_USER_IDX` ON `BOARD_RECOMMEND` (`user_idx`);
CREATE INDEX `IDX_COMMENT_USER_IDX` ON `COMMENT` (`user_idx`);
CREATE INDEX `IDX_COMMENT_BOARD_IDX` ON `COMMENT` (`board_idx`);
CREATE INDEX `IDX_COMMENT_RECOMMEND_COMMENT_IDX` ON `COMMENT_RECOMMEND` (`comment_idx`);
CREATE INDEX `IDX_COMMENT_RECOMMEND_USER_IDX` ON `COMMENT_RECOMMEND` (`user_idx`);
CREATE INDEX `IDX_TRANSACTION_USER_IDX` ON `TRANSACTION` (`user_idx`);
CREATE INDEX `IDX_TRANSACTION_PORTFOLIO_IDX` ON `TRANSACTION` (`portfolio_idx`);
CREATE INDEX `IDX_TRANSACTION_ASSET_IDX` ON `TRANSACTION` (`ASSET_IDX`);
CREATE INDEX `IDX_BOOKMARK_USER_IDX` ON `BOOKMARK` (`user_idx`);
CREATE INDEX `IDX_BOOKMARK_ASSET_IDX` ON `BOOKMARK` (`asset_idx`);

-- ALTER TABLE `board` ADD CONSTRAINT `fk_board_user` FOREIGN KEY (`user_idx`) REFERENCES `user` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `board_recommend` ADD CONSTRAINT `fk_board_recommend_board` FOREIGN KEY (`board_idx`) REFERENCES `board` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `board_recommend` ADD CONSTRAINT `fk_board_recommend_user` FOREIGN KEY (`user_idx`) REFERENCES `user` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `comment` ADD CONSTRAINT `fk_comment_user` FOREIGN KEY (`user_idx`) REFERENCES `user` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `comment` ADD CONSTRAINT `fk_comment_board` FOREIGN KEY (`board_idx`) REFERENCES `board` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `comment_recommend` ADD CONSTRAINT `fk_comment_recommend_comment` FOREIGN KEY (`comment_idx`) REFERENCES `comment` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `comment_recommend` ADD CONSTRAINT `fk_comment_recommend_user` FOREIGN KEY (`user_idx`) REFERENCES `user` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `user_roles` ADD CONSTRAINT `fk_user_roles_user` FOREIGN KEY (`user_idx`) REFERENCES `user` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `user_roles` ADD CONSTRAINT `fk_user_roles_roles` FOREIGN KEY (`roles_idx`) REFERENCES `roles` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `roles_authority` ADD CONSTRAINT `fk_roles_authority_roles` FOREIGN KEY (`roles_idx`) REFERENCES `roles` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `roles_authority` ADD CONSTRAINT `fk_roles_authority_authority` FOREIGN KEY (`authority_idx`) REFERENCES `authority` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `board_report` ADD CONSTRAINT `fk_board_report_board` FOREIGN KEY (`board_idx`) REFERENCES `board` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `board_report` ADD CONSTRAINT `fk_board_report_user` FOREIGN KEY (`user_idx`) REFERENCES `user` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `comment_report` ADD CONSTRAINT `fk_comment_report_comment` FOREIGN KEY (`comment_idx`) REFERENCES `comment` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `comment_report` ADD CONSTRAINT `fk_comment_report_user` FOREIGN KEY (`user_idx`) REFERENCES `user` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `portfolio` ADD FOREIGN KEY (`user_idx`) REFERENCES `user` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `portfolio_detail` ADD FOREIGN KEY (`portfolio_idx`) REFERENCES `portfolio` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `portfolio_detail` ADD FOREIGN KEY (`asset_idx`) REFERENCES `asset` (`idx`);
-- ALTER TABLE `transaction` ADD FOREIGN KEY (`user_idx`) REFERENCES `user` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `transaction` ADD FOREIGN KEY (`asset_idx`) REFERENCES `asset` (`idx`);
-- ALTER TABLE `transaction` ADD FOREIGN KEY (`portfolio_idx`) REFERENCES `portfolio` (`idx`);
-- ALTER TABLE `bookmark` ADD FOREIGN KEY (`user_idx`) REFERENCES `user` (`idx`) ON DELETE CASCADE;
-- ALTER TABLE `bookmark` ADD FOREIGN KEY (`asset_idx`) REFERENCES `asset` (`idx`);
-- ALTER TABLE `asset` ADD FOREIGN KEY (`type_idx`) REFERENCES `asset_type` (`idx`);

ALTER TABLE `BOARD` ADD CONSTRAINT `FK_BOARD_USER` FOREIGN KEY (`USER_IDX`) REFERENCES `USER` (`IDX`) ON DELETE CASCADE;

-- BOARD_RECOMMEND 테이블
ALTER TABLE `BOARD_RECOMMEND` ADD CONSTRAINT `FK_BOARD_RECOMMEND_BOARD` FOREIGN KEY (`BOARD_IDX`) REFERENCES `BOARD` (`IDX`) ON DELETE CASCADE;
ALTER TABLE `BOARD_RECOMMEND` ADD CONSTRAINT `FK_BOARD_RECOMMEND_USER` FOREIGN KEY (`USER_IDX`) REFERENCES `USER` (`IDX`) ON DELETE CASCADE;

-- BOARD_REPORT 테이블
ALTER TABLE `BOARD_REPORT` ADD CONSTRAINT `FK_BOARD_REPORT_BOARD` FOREIGN KEY (`BOARD_IDX`) REFERENCES `BOARD` (`IDX`) ON DELETE CASCADE;
ALTER TABLE `BOARD_REPORT` ADD CONSTRAINT `FK_BOARD_REPORT_USER` FOREIGN KEY (`USER_IDX`) REFERENCES `USER` (`IDX`) ON DELETE CASCADE;

-- COMMENT 테이블
ALTER TABLE `COMMENT` ADD CONSTRAINT `FK_COMMENT_USER` FOREIGN KEY (`USER_IDX`) REFERENCES `USER` (`IDX`) ON DELETE CASCADE;
ALTER TABLE `COMMENT` ADD CONSTRAINT `FK_COMMENT_BOARD` FOREIGN KEY (`BOARD_IDX`) REFERENCES `BOARD` (`IDX`) ON DELETE CASCADE;

-- COMMENT_RECOMMEND 테이블
ALTER TABLE `COMMENT_RECOMMEND` ADD CONSTRAINT `FK_COMMENT_RECOMMEND_COMMENT` FOREIGN KEY (`COMMENT_IDX`) REFERENCES `COMMENT` (`IDX`) ON DELETE CASCADE;
ALTER TABLE `COMMENT_RECOMMEND` ADD CONSTRAINT `FK_COMMENT_RECOMMEND_USER` FOREIGN KEY (`USER_IDX`) REFERENCES `USER` (`IDX`) ON DELETE CASCADE;

-- COMMENT_REPORT 테이블
ALTER TABLE `COMMENT_REPORT` ADD CONSTRAINT `FK_COMMENT_REPORT_COMMENT` FOREIGN KEY (`COMMENT_IDX`) REFERENCES `COMMENT` (`IDX`) ON DELETE CASCADE;
ALTER TABLE `COMMENT_REPORT` ADD CONSTRAINT `FK_COMMENT_REPORT_USER` FOREIGN KEY (`USER_IDX`) REFERENCES `USER` (`IDX`) ON DELETE CASCADE;

-- PORTFOLIO 테이블
ALTER TABLE `PORTFOLIO` ADD CONSTRAINT `FK_PORTFOLIO_USER` FOREIGN KEY (`USER_IDX`) REFERENCES `USER` (`IDX`) ON DELETE CASCADE;

-- PORTFOLIO_DETAIL 테이블
ALTER TABLE `PORTFOLIO_DETAIL` ADD CONSTRAINT `FK_PORTFOLIO_DETAIL_PORTFOLIO` FOREIGN KEY (`PORTFOLIO_IDX`) REFERENCES `PORTFOLIO` (`IDX`) ON DELETE CASCADE;
ALTER TABLE `PORTFOLIO_DETAIL` ADD CONSTRAINT `FK_PORTFOLIO_DETAIL_ASSET` FOREIGN KEY (`ASSET_IDX`) REFERENCES `ASSET` (`IDX`);

-- TRANSACTION 테이블
ALTER TABLE `TRANSACTION` ADD CONSTRAINT `FK_TRANSACTION_USER` FOREIGN KEY (`USER_IDX`) REFERENCES `USER` (`IDX`) ON DELETE CASCADE;
ALTER TABLE `TRANSACTION` ADD CONSTRAINT `FK_TRANSACTION_PORTFOLIO` FOREIGN KEY (`PORTFOLIO_IDX`) REFERENCES `PORTFOLIO` (`IDX`) ON DELETE CASCADE;
ALTER TABLE `TRANSACTION` ADD CONSTRAINT `FK_TRANSACTION_ASSET` FOREIGN KEY (`ASSET_IDX`) REFERENCES `ASSET` (`IDX`);

-- BOOKMARK 테이블
ALTER TABLE `BOOKMARK` ADD CONSTRAINT `FK_BOOKMARK_USER` FOREIGN KEY (`USER_IDX`) REFERENCES `USER` (`IDX`) ON DELETE CASCADE;
ALTER TABLE `BOOKMARK` ADD CONSTRAINT `FK_BOOKMARK_ASSET` FOREIGN KEY (`ASSET_IDX`) REFERENCES `ASSET` (`IDX`);